name: Deploy Angular to VPS

on:
  push:
    branches:
      - master  # Usás master en lugar de main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: npm install

      - name: Create environment files
        run: |
          mkdir -p src/environments
          echo "export const environment = { production: true, apiUrl: '${{ secrets.API_URL }}' };" > src/environments/environment.prod.ts
          echo "export const environment = { production: false, apiUrl: '${{ secrets.API_URL_DEV }}' };" > src/environments/environment.ts

      - name: Build Angular app
        run: npm run build --prod

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/ci_deploy_key
          chmod 600 ~/.ssh/ci_deploy_key

      - name: Deploy to VPS via SSH
        run: |
          rsync -avz -e "ssh -i ~/.ssh/ci_deploy_key -o StrictHostKeyChecking=no -p5507" \
          dist/devtacora/browser/ root@149.50.150.50:/var/www/devtacora-back/dist/public/